REMOTE_URL:
- file:///opt/spaceone/identity/config/database.yaml
- file:///opt/spaceone/identity/config/shared.yaml
- file:///opt/spaceone/identity/config/application.yaml
GLOBAL:
  MAX_WORKERS: 1000
  DATABASES:
    default:
      db: identity
      host: mongodb
      port: 27017
      maxPoolSize: 200
      username: identity_user
      password: identity_password
  CACHES:
    default:
      backend: spaceone.core.cache.redis_cache.RedisCache
      host: redis
      port: 6379
      db: 1
      encoding: utf-8
      socket_timeout: 10
      socket_connect_timeout: 10
  LOG:
    loggers:
      spaceone:
        handlers:
          - console
          - file
    handlers:
      file:
        type: file
        filename: /var/log/spaceone/identity.log
    filters:
      masking:
        rules:
          DomainOwner.create:
            - password
            - email
            - mobile
          DomainOwner.update:
            - password
            - email
            - mobile
          User.create:
            - password
            - email
            - mobile
          User.update:
            - password
            - email
            - mobile
          Token.issue:
            - credentials

  HANDLERS:
    authentication:
    - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
      uri: grpc://identity:50051/v1/Domain/get_public_key
    authorization:
    - backend: spaceone.core.handler.authorization_handler.AuthorizationGRPCHandler
      uri: grpc://identity:50051/v1/Authorization/verify
